### ISSUE TITLE
Blazor localization in a razor library

### ISSUE THREAD

**Issue by snelsn04** [IEvangelist/blazor-azure-openai#17]
We have a Blazor web application that has the Localization App Toolkit setup and working. Now we have moved some of the controls to a razor library to allow them to easily be shared by more solutions. I was able to configure the Localization for the library, but not able to get the localization to pick up the values for the library. We are interested in this approach to keep everything encapsulated in the library. Any suggestions to get this to work would be appreciated.

**Comment by IEvangelist** [comment]
Hi @snelsn04 - do you have any examples I can see, I'm not sure I follow where the resource files are located relative to the app. That could be helpful to understand.
